spice_mix = set()
print(f"Initial spice_mix : {(spice_mix)}")
print(f"Initial spice_mix ID : {id(spice_mix)}")
spice_mix.add("Ginger")
spice_mix.add("Cardamom")
spice_mix.add("Lemon")
print(f"After spice_mix : {(spice_mix)}")
print(f"After spice_mix ID : {id(spice_mix)}")
